name: Node.js CI/CD

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+-dev', 'v[0-9]+.[0-9]+.[0-9]+-stg', 'v[0-9]+.[0-9]+.[0-9]+-prod']

  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    name: Call another workflow passing data
    uses: hungds99/aws-radar/.github/workflows/main.yml@main
    with:
      APP_ID: deli
      APP_ENV: TEST
    secrets:
      API_KEY: '123456'
