name: Deploy Deli Application

on:
  workflow_call:
    inputs:
      APP_ID:
        required: false
        type: string
      APP_ENV:
        required: false
        type: string
    secrets:
      API_KEY:
        required: false

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The app id is ${{ inputs.APP_ID }}"
