name: Node.js CI/CD

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+-dev', 'v[0-9]+.[0-9]+.[0-9]+-stg', 'v[0-9]+.[0-9]+.[0-9]+-prod']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - run: echo "Hello World!"
